# Generated by Django 4.2.6 on 2023-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('display_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
