# Generated by Django 4.2.6 on 2023-11-01 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('display_board', '0002_alter_slide_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='name',
            new_name='title',
        ),
    ]
