# Generated by Django 4.2.6 on 2023-11-01 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('display_board', '0003_rename_name_slide_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='title',
            new_name='name',
        ),
    ]
