# Generated by Django 4.2.6 on 2023-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('display_board', '0009_alter_slide_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=7),
        ),
    ]
