# Generated by Django 4.2.6 on 2023-12-17 18:37

from django.db import migrations, models
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "key",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "key",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "key",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=120)),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineer"),
                            ("PM", "Program Manager"),
                            ("OP", "Operator"),
                            ("MT", "Maintenance"),
                        ],
                        default="ENG",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TesterSection",
            fields=[
                (
                    "keyTesterSection",
                    models.CharField(
                        default=scheduler.models.generate_unique_id,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("open", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testerselections",
                        to="scheduler.testersection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tester",
            fields=[
                (
                    "key",
                    models.CharField(
                        default=scheduler.models.generate_unique_id,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testers",
                        to="scheduler.testersection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("text", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("job_number", models.CharField(blank=True, max_length=120)),
                ("locked", models.BooleanField(default=False)),
                ("window_lot", models.BooleanField(default=False)),
                ("number_units", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineer"),
                            ("PROD", "Production"),
                            ("CAL", "Calibration"),
                            ("MT", "Maintenance"),
                        ],
                        default="PROD",
                        max_length=4,
                    ),
                ),
                ("steps", models.CharField(blank=True, max_length=120)),
                ("peripherals", models.CharField(blank=True, max_length=120)),
                ("test_temps", models.CharField(blank=True, max_length=120)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="scheduler.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="scheduler.device",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="scheduler.people",
                    ),
                ),
                (
                    "tester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="scheduler.tester",
                    ),
                ),
            ],
        ),
    ]
